name: 'Data Leak Action'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: install dependencies
      run:  pip install yara-python

    - name: run action script
      run: python action.py 
