name: 'Data Leak Action'

on:
  push:
    branches-ignore: none
  pull_request:
    branches-ignore: none

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: run remote script
      uses: joocer/action@master   
