name: 'Data Leak Action'

on:
  push:
    branches-ignore: none
  pull_request:
    branches-ignore: none

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: install dependencies
      run:  pip install yara-python

    - name: run action script
      run: python $GITHUB_WORKSPACE/action.py 
